wordpress:
 image: wordpress
 links:
  - mariadb:mysql
 environment: 
  - WORDPRESS_DB_PASSWORD=Theasker
 ports: 
  - "8000:80"
 volumes:
  - ./html:/var/www/html

mariadb:
 image: mariadb
 environment: 
  - MYSQL_ROOT_PASSWORD=Theasker
  - MYSQL_DATABASE=wordpress
 volumes: 
  - ./database:/var/lib/mysql